### ISSUE TITLE
Windows Install

### ISSUE THREAD

**Issue by stinodes** [radarlabs/s2#11]
Hi there,

After installing necessary build-tools, I am getting swarmed by a ton on errors during the post-install build.  
I have provided a small snippet to try and illustrate the type of errors I am getting, though they are filling up my buffer entirely. 

Some more info:
* Windows 10 Build 17763.805
* Node 10.16.0
* Tried with both Python 2.7.16
* windows-build-tools 5.2.2

Cheers!

Error snippet:
```
  c:\users\<...>\node_modules\@radarlabs\s2\third_party\s2geometry\src\s2\s1angle.h(195): note: failure was caused by control reaching the end of a constexpr function (compiling source file ..\third_party\s2geometry\src\s2\s2wedge_relations.cc)                                                                         
      c:\users\<...>\node_modules\@radarlabs\s2\third_party\s2geometry\src\s2\s1angle.h( 307): error C2065: 'M_PI': undeclared identifier (compiling source file ..\third_party\s2geometry\src\s2\s2wedge_relati ons.cc) [C:\Users\<...>\node_modules\@radarlabs\s2\build\s2.vcxproj]              
      c:\users\<...>\node_modules\@radarlabs\s2\third_party\s2geometry\src\s2\base\port.h(74): fatal error C1189: #error:  chars must be unsigned!  Use the /J flag on the compiler command line.  // NOLINT (c ompiling source file ..\third_party\s2geometry\src\s2\s2text_format.cc) [C:\Users\<...>\node_modules\@radarlabs\s2\build\s2.vcxproj]  
```

**Comment by jkao** [comment]
Hey! 

Unfortunately, we haven't tested compiling this library on Windows (and don't really have one at hand at the moment), so our best workaround right now for you is to build this with [Docker](https://docs.docker.com/docker-for-windows/install/).

The official library from Google doesn't seem to have been tested with Windows, either, unfortunately: https://github.com/google/s2geometry

```
Thorough testing has only been done on Ubuntu 14.04.3 and macOS 10.12.
```

If you want a crack at it, the best bet is to see if you can build the `s2geometry` library on your machine and then play around with the configuration for the node-gyp tool here if that's building:  https://github.com/radarlabs/s2/blob/master/binding.gyp

Cheers,
Jeff

**Comment by stinodes** [comment]
Thanks for the response!

I hadn't seen that Google's original lib also hasn't been built using windows yet. Kind of a bummer.
Sadly my experience with the tech they use is close to zero, so I doubt I'd be able to contribute anything useful there.

I'll give it a shot when I have the time, though, and will go from there if I get anywhere.

**Comment by sravanireddyl** [comment]
Any update on windows OS compatibility?

I am trying to use this module in my project. Or there any alternatives to code in windows OS to continue with this npm module?

**Comment by jkao** [comment]
I think there's still some issues with building this on the Windows side from Google: https://github.com/google/s2geometry/issues/38

Two workarounds would be:

- use Docker or a virtual machine with Linux
- use a pure JavaScript version (for e.g. https://github.com/vekexasia/nodes2-ts)
