### ISSUE TITLE
Can I use this library to make a UDF in BigQuery?

### ISSUE THREAD

**Issue by XavierLavenir** [radarlabs/s2#18]
Hello,

Thanks for the library, it's really useful. I use S2 cells a lot within BigQuery and it would be really useful to be able to access these functions directly within BigQuery. 

Is it possible to do so? I've bundled a javascript library before and uploaded it to the Google Cloud Bucket which allowed me to access the functions, but i'm not sure if I can do it with this library if it contains bindings.

Any help would be really appreciated.

Thanks,
Xavier

**Comment by jkao** [comment]
Hi Xavier,

I think BigQuery UDFs need to be in pure JavaScript. Given that, our library won't work for this use case, and it may be worth exploring this library: https://www.npmjs.com/package/s2-geometry

Let me know how it goes.

Cheers,
Jeff

**Comment by schedutron** [comment]
https://www.npmjs.com/package/s2-geometry doesn't seem to have region coverer capabilities - which are there in @radarlabs/s2 library. Can you please help on how to achieve region covering with s2-geometry library? My use case is that I want to list cell IDs that overlap with a circle of given radius and center.

I managed to bundle the @radarlabs/s2 code using webpack and then upload the minified file to a GCS bucket, but that didn't work as Google doesn't allow JS library file sizes > 1Mb.
