### ISSUE TITLE
Missing Expected Exports

### ISSUE THREAD

**Issue by kevin-kelly-centivo** [radarlabs/s2#19]
Missing classes such as S1Angle etc. Was curious why these are not a part of the repo. 

Thank you, 
Kevin

**Comment by jkao** [comment]
Hey Kevin,

Thanks for your interest in the S2 Library. We haven't found a use-case for the S1Angle class yet, but happy to review and accept PRs. Here's an example of how to bind one of the classes to the library: https://github.com/radarlabs/s2/pull/9/files


Cheers,
Jeff

**Comment by jkao** [comment]
Closing this for now.
