### ISSUE TITLE
cellunion contains method not working 

### ISSUE THREAD

**Issue by vivek8690** [radarlabs/s2#23]
for [ -122.435577, 37.751363] this location I am creating radius covering[s2.RegionCoverer.getRadiusCovering] cellunion with 500 m radius 
and I am trying that cell  union contains this point  [-122.434339,37.751433 ]
It returns false every time
I tried same scenario for other locations as well but it was working for them

**Comment by jkao** [comment]
Hi Vivek thanks for submitting an issue!

This is dependent on the parameters you pass to RegionCoverer as that will determine the S2 Covering. 

You can manually test the region covering here: https://s2.sidewalklabs.com/regioncoverer/

For me to debug, could you post a code snippet of your experiment?
