### ISSUE TITLE
Add pre-built binary for node 14

### ISSUE THREAD

**Issue by wcauchois** [radarlabs/s2#29]
Hi, could you add a pre-built binary for node 14? We just upgraded to 14.15.1 (LTS). Thanks :)

**Comment by jkao** [comment]
Hey, Bill! We're also in the process of upgrading to Node 14, so we'll publish this very soon! 🌚

**Comment by jkao** [comment]
We've published this for 64-bit OSX (darwin) + Linux. Feel free to re-open if you'd like other platforms.
