### ISSUE TITLE
Typos in Readme

### ISSUE THREAD

**Issue by spendres** [radarlabs/s2#54]
1.
**line:** 
const pointAtLevel14 = point.parent(s2Level);
**should be:** 
const pointAtLevel14 = point.parent(s2level); // both lowercase l

2.
**line:** 
console.log(coveringCells.contains(new s2.CellId(s2LatLong)));
**should be:**
console.log(coveringCells.has(new s2.CellId(s2LatLong)));

**Comment by jkao** [comment]
Want to open a PR?

**Comment by spendres** [comment]
I can. Do you have a branch or tag you prefer me to use?

**Comment by jkao** [comment]
We don't have a strict convention for branch names right now. As long as
this issue is back linked in the PR, we should be good to go! :)

**Comment by spendres** [comment]
Okay, just used your current branch. Just committed the update for you to review.

**Comment by jkao** [comment]
it may actually require a fork and a PR against this repo for it to work. I can update it in my existing PR.

**Comment by spendres** [comment]
That will work. It’s a very small change.

**Comment by jkao** [comment]
Fixed: https://github.com/radarlabs/s2/commit/96c395af13f74d449e3ce7f8d1a58a8fde08e350
