### ISSUE TITLE
Deprecation issues - external dependencies

### ISSUE THREAD

**Issue by trobert2** [radarlabs/s2#56]
I was wondering if there are plans to resolve these issues in the future:
```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
```

I see low activity on this project. is there another repo/library where it is being maintained?

**Comment by jkao** [comment]
We'll be spending some time in the next month or so supporting Node 18, so there will be some additional work we'll put in here.

**Comment by jkao** [comment]
Some of these are addressed through our direct-dependency upgrades in this PR: https://github.com/radarlabs/s2/pull/59

However, our dependencies are causing these problematic sub-dependencies. We'll open issues downstream.
