### ISSUE TITLE
Type mismatch - node 19 mac M1 & missing dependency on node 20

### ISSUE THREAD

**Issue by trobert2** [radarlabs/s2#67]
I think there is a type mismatch between the current latest version and the types available on node20.
Using this code Code:
```
export const getLatLonByHash = (hash: string): s2.LatLng => {
  const point = s2.CellId.fromToken(hash)
  const cell = new s2.Cell(point)

  const latlon = new s2.LatLng(cell.getCenter())

  return latlon
}
```
I get this error:
```
  const cell = new s2.Cell(point)
               ^
TypeError: CellId expected.
```
This is currently happening on node 19 and now after updating it happens on node 20 as well.

* node version: v20.2.0
* @radarlabs/s2 version: "0.0.5"

EDIT: I have edited this description to highlight just one issue. the missing `node-v115-darwin-arm64` module was user error.

**Comment by willbattel** [comment]
I'm also running into that error on node 20.

```
Cannot find module '../node_modules/@radarlabs/s2/lib/binding/Release/node-v115-darwin-arm64/s2.node'
```

**Comment by trobert2** [comment]
> I'm also running into that error on node 20. Works with node 18.
> 
> ```
> Cannot find module '../node_modules/@radarlabs/s2/lib/binding/Release/node-v115-darwin-arm64/s2.node'
> ```
here are some things to consider:
* make sure if you have an intermediary library that uses @radarlabs/s2, that it is also upgraded and built with node20 for your platform.
* when upgrading, delete the dependency from your node_modules or the whole node_modules directory. Delete the lock file for your package manager and re-install the dependencies

Doing this fixed the missing binary issue for me. I have updated the description to be more precise to the issue I am having
